# SonarQube Project Configuration
sonar.projectKey=sonar-queue
sonar.projectName=sonar-queue
sonar.projectVersion=1.0.0

# Source & Test paths
sonar.sources=src
# sonar.tests=test

# Exclusions
sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/build/**,\
  **/coverage/**,\
  **/*.d.ts,\
  sonar-project.properties

# Encoding & SCM
sonar.sourceEncoding=UTF-8
sonar.scm.disabled=true
