import { spawnSync, type SpawnSyncOptionsWithStringEncoding } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import readline from 'node:readline';
import { getConfig } from './config.js';

// ─── Constants ───────────────────────────────────────────────────────────────

const CONTAINER_NAME = 'sonarqube';
const DB_CONTAINER_NAME = 'sonarqube-db';
const DEFAULT_PORT = 9100;
const SONARQUBE_VERSION = '26.9.0.129388-community';
const SONARQUBE_DIR = path.join(os.homedir(), '.local', 'share', 'sonar-queue');
const COMPOSE_FILE = path.join(SONARQUBE_DIR, 'compose.yml');

// ─── Compose file content ─────────────────────────────────────────────────────

function buildComposeContent(port: number): string {
  return `# Generated by sonar-queue
# Do not edit manually — use sonar-queue start / stop / reset
services:
  db:
    image: postgres:15-alpine
    container_name: sonarqube-db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - sonarqube_db:/var/lib/postgresql/data
    networks:
      - sonarqube
    restart: unless-stopped

  sonarqube:
    image: sonarqube:${SONARQUBE_VERSION}
    container_name: sonarqube
    depends_on:
      - db
    ports:
      - "127.0.0.1:${port}:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - sonarqube
    restart: unless-stopped

networks:
  sonarqube:

volumes:
  sonarqube_db:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
`;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

const DEFAULT_EXEC_OPTIONS: SpawnSyncOptionsWithStringEncoding = { encoding: 'utf-8' };
let cachedDockerPath: string | null = null;

function getDockerPath(): string {
  if (cachedDockerPath) return cachedDockerPath;
  const candidates = [
    '/usr/bin/docker',
    '/usr/local/bin/docker',
    '/opt/homebrew/bin/docker',
  ];
  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) {
      cachedDockerPath = candidate;
      return candidate;
    }
  }
  cachedDockerPath = 'docker';
  return cachedDockerPath;
}

function execDocker(
  args: string[],
  options?: SpawnSyncOptionsWithStringEncoding
) {
  const opts = options ?? DEFAULT_EXEC_OPTIONS;
  return spawnSync(getDockerPath(), args, opts);
}

function getPort(): number {
  try {
    const { hostUrl } = getConfig();
    return Number.parseInt(new URL(hostUrl).port, 10) || DEFAULT_PORT;
  } catch {
    return DEFAULT_PORT;
  }
}

function dockerAvailable(): boolean {
  try {
    return execDocker(['--version'], { encoding: 'utf-8', timeout: 3000 }).status === 0;
  } catch {
    return false;
  }
}

function composeAvailable(): boolean {
  try {
    return (
      execDocker(['compose', 'version'], { encoding: 'utf-8', timeout: 3000 }).status === 0
    );
  } catch {
    return false;
  }
}

type ContainerState = 'running' | 'stopped' | 'none';

function getContainerState(name: string): ContainerState {
  try {
    const res = execDocker(['inspect', '--format', '{{.State.Status}}', name], {
      encoding: 'utf-8',
      timeout: 3000,
    });
    if (res.status !== 0) return 'none';
    const status = (res.stdout || '').trim().toLowerCase();
    if (status === 'running') return 'running';
    return 'stopped';
  } catch {
    return 'none';
  }
}

function containerStatus(): ContainerState {
  const app = getContainerState(CONTAINER_NAME);
  const db = getContainerState(DB_CONTAINER_NAME);
  if (app === 'running' && db === 'running') return 'running';
  if (app !== 'none' || db !== 'none') return 'stopped';
  return 'none';
}

function ensureComposeFile(port: number): void {
  if (!fs.existsSync(SONARQUBE_DIR)) {
    fs.mkdirSync(SONARQUBE_DIR, { recursive: true });
  }
  if (!fs.existsSync(COMPOSE_FILE)) {
    fs.writeFileSync(COMPOSE_FILE, buildComposeContent(port), 'utf-8');
    console.log(`  Created: ${COMPOSE_FILE}`);
  }
}

function runCompose(composeArgs: string[]): number | null {
  const result = execDocker(['compose', '-f', COMPOSE_FILE, ...composeArgs], {
    encoding: 'utf-8',
    stdio: 'inherit',
  });
  return result.status;
}

// ─── Handlers ─────────────────────────────────────────────────────────────────

function startContainer(name: string): boolean {
  const res = execDocker(['start', name], {
    encoding: 'utf-8',
    stdio: 'inherit',
  });
  if (res.status !== 0) {
    console.error(`\nFailed to start ${name} container.`);
    process.exitCode = 1;
    return false;
  }
  return true;
}

function startExistingContainers(
  appState: ContainerState,
  dbState: ContainerState
): boolean {
  if (dbState !== 'running' && !startContainer(DB_CONTAINER_NAME)) {
    return false;
  }
  if (appState !== 'running' && !startContainer(CONTAINER_NAME)) {
    return false;
  }
  return true;
}

function handleContainerConflict(appState: ContainerState): void {
  const existing = appState !== 'none' ? CONTAINER_NAME : DB_CONTAINER_NAME;
  const missing = appState !== 'none' ? DB_CONTAINER_NAME : CONTAINER_NAME;
  console.error(`Conflict: Container "${existing}" already exists, but "${missing}" does not.`);
  console.error('To re-provision cleanly, run: sonar-queue docker-reset && sonar-queue start');
  console.error(`Or remove the conflicting container: docker rm -f ${existing}`);
  process.exitCode = 1;
}

function provisionWithCompose(): boolean {
  if (!composeAvailable()) {
    console.error('Error: Docker Compose (v2) not available.');
    console.error('Update Docker or install the Compose plugin.');
    process.exitCode = 1;
    return false;
  }

  ensureComposeFile(getPort());

  const code = runCompose(['up', '-d']);
  if (code !== 0) {
    console.error('\nFailed to start SonarQube.');
    process.exitCode = 1;
    return false;
  }
  return true;
}

function startSonarQube(
  appState: ContainerState,
  dbState: ContainerState
): boolean {
  if (appState !== 'none' && dbState !== 'none') {
    return startExistingContainers(appState, dbState);
  }

  if (appState !== 'none' || dbState !== 'none') {
    handleContainerConflict(appState);
    return false;
  }

  return provisionWithCompose();
}

function printStartupBanner(hostUrl: string): void {
  console.log('');
  console.log(`SonarQube starting at ${hostUrl}`);
  console.log('  → PostgreSQL: internal Docker network (not exposed to host)');
  console.log(`  → SonarQube:  ${hostUrl}  (may take 30–60 s to be ready)`);
  console.log('');
  console.log('Check readiness:   sonar-queue doctor');
}

export function handleStart(_args: string[]): void {
  if (!dockerAvailable()) {
    console.error('Error: Docker not found in PATH.');
    console.error('Install Docker and try again: https://docs.docker.com/engine/install/');
    process.exitCode = 1;
    return;
  }

  const config = getConfig();
  const appState = getContainerState(CONTAINER_NAME);
  const dbState = getContainerState(DB_CONTAINER_NAME);

  if (appState === 'running' && dbState === 'running') {
    console.log(`SonarQube already running at ${config.hostUrl}`);
    return;
  }

  console.log('Starting SonarQube...\n');

  if (!startSonarQube(appState, dbState)) {
    return;
  }

  printStartupBanner(config.hostUrl);
}


export function handleStop(): void {
  if (!dockerAvailable()) {
    console.error('Error: Docker not found in PATH.');
    process.exitCode = 1;
    return;
  }

  const appState = getContainerState(CONTAINER_NAME);
  const dbState = getContainerState(DB_CONTAINER_NAME);

  if (appState === 'none' && dbState === 'none') {
    console.log('No SonarQube container found.');
    return;
  }
  if (appState === 'stopped' && dbState === 'stopped') {
    console.log('SonarQube is already stopped.');
    return;
  }

  console.log('Stopping SonarQube...');

  const toStop: string[] = [];
  if (appState === 'running') toStop.push(CONTAINER_NAME);
  if (dbState === 'running') toStop.push(DB_CONTAINER_NAME);

  if (toStop.length > 0) {
    const res = execDocker(['stop', ...toStop], { encoding: 'utf-8', stdio: 'inherit' });
    if (res.status !== 0) {
      console.error('Failed to stop SonarQube.');
      process.exitCode = 1;
      return;
    }
  }

  console.log('');
  console.log('SonarQube stopped.');
  console.log('Persistent data preserved. (volumes: sonarqube_db, sonarqube_data, …)');
}

export function handleRestart(_args: string[]): void {
  handleStop();
  console.log('');
  handleStart([]);
}

export async function handleReset(_args: string[]): Promise<void> {
  if (!dockerAvailable()) {
    console.error('Error: Docker not found in PATH.');
    process.exitCode = 1;
    return;
  }

  console.log('');
  console.log('⚠  WARNING');
  console.log('');
  console.log('This will permanently delete:');
  console.log('  • SonarQube database (all scan history)');
  console.log('  • SonarQube analysis data and configuration');
  console.log('  • SonarQube logs and extensions');
  console.log('');
  console.log('This operation CANNOT be undone.');
  console.log('');

  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  const answer = await new Promise<string>((resolve) =>
    rl.question('Continue? [y/N] ', resolve)
  );
  rl.close();

  if (answer.trim().toLowerCase() !== 'y') {
    console.log('Aborted. No changes made.');
    return;
  }

  console.log('\nRemoving containers and volumes...');

  if (fs.existsSync(COMPOSE_FILE)) {
    runCompose(['down', '-v']);
  }

  execDocker(['stop', CONTAINER_NAME, DB_CONTAINER_NAME], { encoding: 'utf-8' });
  execDocker(['rm', '-f', CONTAINER_NAME, DB_CONTAINER_NAME], { encoding: 'utf-8' });
  for (const vol of [
    'sonarqube_db',
    'sonarqube_data',
    'sonarqube_extensions',
    'sonarqube_logs',
  ]) {
    execDocker(['volume', 'rm', '-f', vol], { encoding: 'utf-8' });
  }

  if (fs.existsSync(COMPOSE_FILE)) {
    fs.unlinkSync(COMPOSE_FILE);
  }

  console.log('');
  console.log('Reset complete. Run: sonar-queue start   to provision a fresh instance.');
}

export function handleDockerStatus(): void {
  if (!dockerAvailable()) {
    console.log('Docker: not found');
    return;
  }

  const appState = getContainerState(CONTAINER_NAME);
  const dbState = getContainerState(DB_CONTAINER_NAME);
  const config = getConfig();

  console.log(`SonarQube container:  ${appState}`);
  console.log(`PostgreSQL container: ${dbState}`);
  if (appState === 'running') {
    console.log(`URL: ${config.hostUrl}`);
    // Show uptime from docker inspect
    try {
      const r = execDocker(['inspect', '--format', '{{.State.StartedAt}}', CONTAINER_NAME], {
        encoding: 'utf-8',
        timeout: 3000,
      });
      if (r.status === 0 && r.stdout.trim()) {
        const started = new Date(r.stdout.trim());
        const uptimeSec = Math.floor((Date.now() - started.getTime()) / 1000);
        const h = Math.floor(uptimeSec / 3600);
        const m = Math.floor((uptimeSec % 3600) / 60);
        const s = uptimeSec % 60;
        console.log(`Uptime: ${h}h ${m}m ${s}s`);
      }
    } catch {
      // Skip uptime
    }
  }
}
